- name: Copy jdk pack
  copy: src=jdk.tar dest=/home/ owner=root group=root  mode='0755' force=no

- name: Unzip jdk pack
  unarchive: src=/home/jdk.tar dest=/home/ owner=root group=root  mode='0755' creates=/home/jdk remote_src=yes

- name: Set jdk env
  template: src=java.sh.j2 dest=/home/java.sh owner=root group=root  mode='0755'

- name: Source bash_profile
  shell: "sh /home/java.sh"
  register: java_version
  tags: t3

- name: display java version
  debug: msg={{java_version.stdout_lines}}
  tags: t3
